### ISSUE TITLE
when catapults are outlawed...

### ISSUE THREAD

**Issue by malfeasancenope** [ivolo/disposable-email-domains#251] opened 2017-11-10 02:27 UTC
I use disposable email address services to either one-off signup for a short used service, or more importantly test for spam

Ostensibly,  sites want an email address to pass updates for a service like a forum.  DEA need arose as the ethically impaired abused these two English words:

Opt

Free 

Agreeing tacitly for you to make choices for me is not me opting.  That's at best coercion.  Provide your plan and explain the impact to me so I may offer INFORMED CONSENT.  

Free: without cost.  Not all costs are monetary. 

If the planned abuse of my privacy was a rare occurrence I would not invest thought, sweat, and money into improving DEA systems.

"But but spammers," you whine. 

As with other law-breakers no amount of additional laws will compel justice.  They will continue being law-breakers.  This is why 'gun control' is equally absurd.  

_when catapults are outlawed only outlaws will have catapults._

Stop tormenring people who are defending their sacrosanct privacy using DEA.

**Comment by danhstevens** [comment] 2017-11-10 02:57
Duplicate of https://github.com/ivolo/disposable-email-domains/issues/26.

**Closed by danhstevens** 2017-11-10 02:57 UTC
